masteos/apollon-localization

- langs/fr_FR.json
> feat(onboarding): step email

- langs/fr_FR.json
```diff
- Mensualité / loyer mensuel
+ Loyer mensuel hors charges
```
> fix(Financial): Update financial key for phase 1

- langs/fr_FR.json
> fix(financial): update financial wording key

- langs/fr_FR.json
```diff
- Cash-flow annuel avant impôt
+ Excédent de trésorerie annuel
```
> fix(financialTab): annual cashflow key

- langs/fr_FR.json
```diff
- Prix de revente du bien projeté sur {{resellingYear}} ans à un taux d'évolution annuel du foncier de {{evaluationRate}} %
+ Prix de revente du bien projeté sur {{resellingYear}} ans à un taux d'évolution annuel du foncier de {{evaluationRate}}
```
> fix(financial): Fix type error, % twice

- langs/fr_FR.json
```diff
- Vous rencontrez un conseiller et accédez à nos opportunités d'investissements locatifs.
+ Rencontrez un conseiller pour discuter de votre projet
```
```diff
- Vous êtes alerté en temps réel des nouvelles opportunités qui correspondent à vos critères.
+ Découvrez des projets qui correspondent à vos attentes
```
```diff
- Vous gérez toutes les étapes de votre investissement depuis l'interface : signature électronique, upload de document...
+ Réalisez une offre d'achat
```
```diff
- Vous visualisez la performance de votre investissement une fois votre bien en location.
+ Suivez les étapes de votre investissement
```
```diff
- En sélectionnant “Continuer” ci-dessous, j'accepte les 
+ J'accepte les
```
```diff
- Politique de confidentialité
+ Politique de confidentialité de Masteos. …
```
> feat(onboarding): onboarding register

- langs/fr_FR.json
> feat(register): add key to submit button

- langs/fr_FR.json
```diff
+ Rencontrez un conseiller pour discuter de votre projet
```
```diff
+ Découvrez des projets qui correspondent à vos attentes
```
```diff
+ Réalisez une offre d’achat
```
```diff
+ Suivez les étapes de votre investissement
```
```diff
- La valeur n'est pas disponible pour cette ville.
```
```diff
- Le prix de l'immobilier a augmenté en moyenne de {{value}} par an sur la zone ces 5 dernières années. Cette valeur n'est pas une prévision des évolutions futures mais permet de donner une tendance sur la zone.
```
> feat(register): new keys for side texte of the register

- .github/scripts/helpers.js
- .github/scripts/stats.js
- .github/workflows/stats.yml
- Handle new file
- Filter file based on folder
- Use markdown collapsable
- Add stats summary
> ci(smart): update to v2

- langs/fr_FR.json
```diff
- Veuillez accepter les conditions générales d’utilisation.
+ Veuillez accepter les conditions générales d’utilisation
```
> feat(register): remove useless dot

- langs/es_ES.json
- langs/fr_BE.json
This pull request was initiated by Lokalise (user Masteos) at 2022-06-16 12:54:13
> feat(inter): translation es & be for new agora variables

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-06-24 10:57:08
> feat(project): Translations update

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-06-24 11:12:30
> fix(project): emoji wasn't shown correctly

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-06-24 17:27:45
> feat(project): view RealEstate button on project page

- langs/fr_BE.json
- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-06-30 12:39:44
> fix(frFR): update of cumulative key

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-06-30 11:54:48
> feat(preview): Add tooltip for net return

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-07-05 11:07:15
> feat(translation): fix project translations

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-07-05 11:47:38
> fix(translation): add missing trailing point

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-07-07 17:34:35
> feat(Lokalise): Translations update

- langs/fr_FR.json
This pull request was initiated by Lokalise (user Masteos) at 2022-07-25 11:10:06
> feat(project): add missing translation for transaction status
